// Assembles the investment memo in code from the structured outputs. The models write the
// arguments; code owns the layout, the numbers table and the disclaimer, so none of it can be hallucinated.
import type { CommitteeResult } from "../orchestrator/types.js";
import type { AnalystReport } from "../schemas/committee.js";

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const pct = (x: number) => `${Math.round(x * 100)}%`;

function reportSection(r: AnalystReport, model: string | undefined): string[] {
  const lines = [`### ${cap(r.analyst)}: ${r.stance.toUpperCase()} (confidence ${pct(r.confidence)})`];
  if (model) lines.push(`_Model: ${model}_`);
  lines.push("", `**${r.headline}**`, "", ...r.keyPoints.map((p) => `- ${p}`), "");
  lines.push("| Metric | Value | Interpretation |", "|---|---|---|");
  lines.push(...r.evidence.map((e) => `| ${e.metric} | ${e.value} | ${e.interpretation.replace(/\|/g, "/")} |`));
  if (r.concerns.length) lines.push("", `_What could make this view wrong:_ ${r.concerns.join("; ")}`);
  return lines;
}

export function buildMemo(result: Omit<CommitteeResult, "memoMarkdown">): string {
  const { snapshot: s, decision: d } = result;
  const modelOf = (id: string) => result.agents.find((a) => a.id === id)?.model;
  const lines: string[] = [];

  lines.push(`# Investment Committee Memo: ${s.ticker} (${s.companyName})`, "");
  lines.push(`**Date:** ${result.generatedAt.slice(0, 10)} · **Data as of:** ${s.asOf} · **Last close:** ${s.facts.technicals["Last close"]}`);
  if (s.sector) lines.push(`**Sector:** ${s.sector}${s.industry ? ` / ${s.industry}` : ""}`);
  lines.push("");

  if (d) {
    lines.push(`## Decision: ${d.recommendation} (confidence ${pct(d.confidence)}, horizon ${d.timeHorizon})`);
    lines.push("", d.summary, "", "### Rationale", ...d.rationale.map((r) => `- ${r}`));
    lines.push("", "### Dissent");
    lines.push(d.dissent ? `> **${cap(d.dissent.analyst)} analyst:** ${d.dissent.argument}` : "_No dissent recorded: the committee was unanimous._");
    lines.push("", "### Key risks", ...d.keyRisks.map((r) => `- ${r}`));
  } else {
    lines.push("## Decision: not available", "", `The chair could not reach a valid decision: ${result.chairError ?? "unknown error"}.`);
  }

  lines.push("", "## Analyst reports", "");
  for (const r of result.reports) lines.push(...reportSection(r, modelOf(r.analyst)), "");
  for (const e of result.analystErrors) lines.push(`### ${cap(e.analyst)}: no report`, `_${e.message}_`, "");

  if (result.rebuttals.length) {
    lines.push("## Rebuttal round", "");
    for (const r of result.rebuttals) {
      lines.push(`- **${cap(r.analyst)} → ${cap(r.respondingTo)}**${r.stanceChanged ? " _(stance changed)_" : ""}: ${r.response}`);
    }
    lines.push("");
  }

  lines.push("## Committee cost", "", "| Agent | Model | Tokens (in/out) | Latency | Cost (USD) |", "|---|---|---|---|---|");
  for (const c of result.costs.calls) {
    lines.push(
      `| ${c.agent}${c.attempt > 1 ? " (retry)" : ""} | ${c.model} | ${c.promptTokens}/${c.completionTokens} | ${(c.latencyMs / 1000).toFixed(1)}s | $${c.estimatedCostUsd.toFixed(5)} |`
    );
  }
  lines.push(`| **Total** | | ${result.costs.totalPromptTokens}/${result.costs.totalCompletionTokens} | | **$${result.costs.totalUsd.toFixed(5)}** |`);

  lines.push("", "## Data sources");
  lines.push(...result.sources.map((src) => `- ${src.name}, fetched ${src.fetchedAt.slice(0, 16).replace("T", " ")} UTC${src.stale ? " (stale cache)" : ""}`));
  lines.push(
    "",
    "---",
    "_Generated by Zenith, an AI investment committee running NVIDIA Nemotron models on Nebius Token Factory. " +
      "All figures are computed in code from market data; the models only interpret them. " +
      "**This is a research and education tool, not financial advice.**_"
  );
  return lines.join("\n");
}
