package com.zenith.thesis;

import com.zenith.schema.ClaimCheck;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** The Counter-Thesis Memo, assembled in code from the structured review (so its layout and disclaimer can't be hallucinated). */
public final class ThesisMemo {

    private ThesisMemo() {}

    private static String label(String id) {
        return switch (id) {
            case "partly_supported" -> "Partly supported";
            default -> id.substring(0, 1).toUpperCase(Locale.ROOT) + id.substring(1);
        };
    }

    public static String build(ThesisService.Result r) {
        var v = r.review();
        List<String> out = new ArrayList<>();
        out.add("# Counter-Thesis Memo: " + r.ticker());
        out.add("");
        out.add("**Date:** " + r.generatedAt().substring(0, 10) + " · **Tested against:** the committee's session of "
                + r.sessionAt().substring(0, 10) + " (call: " + r.call() + ")");
        out.add("");
        out.add("## The investor's thesis");
        out.add("> " + r.thesis());
        out.add("");
        out.add("## Verdict: " + label(v.verdict().id()));
        out.add(v.summary());
        out.add("");
        out.add("## Claim by claim");
        out.add("| Claim | Assessment | Evidence | Source |");
        out.add("|---|---|---|---|");
        for (ClaimCheck c : v.claims()) {
            out.add("| " + cell(c.claim()) + " | " + label(c.assessment().id()) + " | " + cell(c.evidence()) + " | "
                    + (c.analyst() == null ? "-" : label(c.analyst().id())) + " |");
        }
        out.add("");
        out.add("## The case against");
        out.add(v.counterThesis());
        out.add("");
        out.add("## Blind spots");
        v.blindSpots().forEach(b -> out.add("- " + b));
        out.add("");
        out.add("## What would change the picture");
        v.whatWouldChangeIt().forEach(w -> out.add("- " + w));
        out.add("");
        if (!r.untraced().isEmpty()) {
            out.add("_Figures that couldn't be traced to the committee's data or the thesis: " + String.join(", ", r.untraced()) + "._");
            out.add("");
        }
        out.add("---");
        out.add("_Generated by Zenith's chair (NVIDIA Nemotron Ultra on Nebius Token Factory) acting as devil's advocate. "
                + "It uses only the figures computed for the committee. This is a research and education tool, not financial advice._");
        return String.join("\n", out);
    }

    private static String cell(String s) {
        return s.replace("|", "\\|").replace("\n", " ");
    }
}
